version: "3.9"
services:
  api:
    build: .
    container_name: adoptme-api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=adoptme
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: adoptme-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
